Build (Ubuntu 16.04 / make / clang):
    image: ubuntu:16.04
    script:
        - apt-get update -qq && apt-get install -y -qq git make clang
        - CC=clang CXX=clang++ make

Build (Ubuntu 16.04 / make / gcc):
    image: ubuntu:16.04
    script:
        - apt-get update -qq && apt-get install -y -qq git make gcc g++
        - CC=gcc CXX=g++ make

Build (Ubuntu 16.04 / CMake / clang):
    image: ubuntu:16.04
    script:
        - apt-get update -qq && apt-get install -y -qq git cmake clang
        - mkdir build
        - cd build
        - cmake .. -DBUILD_DEMO=OFF -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
        - make

Build Demo (Ubuntu 16.04 / CMake / clang):
    image: ubuntu:16.04
    script:
        - apt-get update -qq && apt-get install -y -qq git cmake clang libglfw3-dev
        - mkdir build
        - cd build
        - cmake .. -DBUILD_DEMO=ON -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
        - make

Build (Ubuntu 16.04 / CMake / gcc):
    image: ubuntu:16.04
    script:
        - apt-get update -qq && apt-get install -y -qq git cmake gcc g++
        - mkdir build
        - cd build
        - cmake .. -DBUILD_DEMO=OFF -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
        - make

Build Demo (Ubuntu 16.04 / CMake / gcc):
    image: ubuntu:16.04
    script:
        - apt-get update -qq && apt-get install -y -qq git cmake gcc g++ libglfw3-dev
        - mkdir build
        - cd build
        - cmake .. -DBUILD_DEMO=ON -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
        - make

Build (Ubuntu 16.10 / make / clang):
    image: ubuntu:16.10
    script:
        - apt-get update -qq && apt-get install -y -qq git make clang
        - CC=clang CXX=clang++ make

Build (Ubuntu 16.10 / make / gcc):
    image: ubuntu:16.10
    script:
        - apt-get update -qq && apt-get install -y -qq git make gcc g++
        - CC=gcc CXX=g++ make

Build (Ubuntu 16.10 / CMake / clang):
    image: ubuntu:16.10
    script:
        - apt-get update -qq && apt-get install -y -qq git cmake clang
        - mkdir build
        - cd build
        - cmake .. -DBUILD_DEMO=OFF -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
        - make

Build Demo (Ubuntu 16.10 / CMake / clang):
    image: ubuntu:16.10
    script:
        - apt-get update -qq && apt-get install -y -qq git cmake clang libglfw3-dev
        - mkdir build
        - cd build
        - cmake .. -DBUILD_DEMO=ON -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
        - make

Build (Ubuntu 16.10 / CMake / gcc):
    image: ubuntu:16.10
    script:
        - apt-get update -qq && apt-get install -y -qq git cmake gcc g++
        - mkdir build
        - cd build
        - cmake .. -DBUILD_DEMO=OFF -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
        - make

Build Demo (Ubuntu 16.10 / CMake / gcc):
    image: ubuntu:16.10
    script:
        - apt-get update -qq && apt-get install -y -qq git cmake gcc g++ libglfw3-dev
        - mkdir build
        - cd build
        - cmake .. -DBUILD_DEMO=ON -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
        - make

Build (Debian 8 / make / clang):
    image: debian:8
    script:
        - apt-get update -qq && apt-get install -y -qq git make clang
        - CC=clang CXX=clang++ make

Build (Debian 8 / make / gcc):
    image: debian:8
    script:
        - apt-get update -qq && apt-get install -y -qq git make gcc g++
        - CC=gcc CXX=g++ make
