sudo: required
dist: trusty
language: cpp


cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.6.2
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.7.1
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.0
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.9.0


matrix:
  include:
    # OSX, xcode 8
    - os: osx
      osx_image: xcode8
      env: CMAKE_OPTIONS="-DBUILD_PYTHON_BINDINGS=ON" PYPI=true
    # Linux, GCC 6
    - os: linux
      env: COMPILER_C=gcc-6 COMPILER_CXX=g++-6 CMAKE_OPTIONS="-DBUILD_PYTHON_BINDINGS=ON" PYPI=true
      compiler: g++
      addons:
        apt:
          packages:
          - g++-6
          - ca-certificates
          - python3.6
          - python3.6-dev
          - python3-pip
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          - sourceline: 'ppa:jonathonf/python-3.6'


before_install:
  # Run homebrew on osx
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  # Setup default versions and override compiler if needed
  - if [[ "${LLVM_VERSION}" == "default" ]]; then LLVM_VERSION=3.9.0; fi
  # Install a recent CMake and Python3 (unless already installed on OS X)
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt-get purge cmake
      DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
      mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
      CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.6.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      cd cmake
      ./bootstrap
      make -j4
      sudo make install
      cmake --version
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      export CC=${COMPILER_C} CXX=${COMPILER_CXX}
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python3 &>/dev/null || brew install python3 && brew postinstall python3; fi
    fi
  # Install needed Python packages
  - sudo pip3 install numpy wheel twine


install:
  - echo "Python package build"
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export VFRENDERING_ADD_VERSION_EXTENSION=true; else export VFRENDERING_ADD_VERSION_EXTENSION=false; fi
  - echo "Add suffix to VFRendering version tag for python package $VFRENDERING_ADD_VERSION_EXTENSION"

  # Build the python package
  - cd ${TRAVIS_BUILD_DIR}
  - python3 setup.py sdist bdist_wheel;


script:
  # Specify account details for PyPI
  - echo "[distutils]"                                 > ~/.pypirc
  - echo "index-servers ="                            >> ~/.pypirc
  - echo "    testpypi"                               >> ~/.pypirc
  - echo "    pypi"                                   >> ~/.pypirc
  - echo "[pypi]"                                     >> ~/.pypirc
  - echo "repository=https://upload.pypi.org/legacy/" >> ~/.pypirc
  - echo "username=$PYPIUSER"                         >> ~/.pypirc
  - echo "password=$PYPIPASSWORD"                     >> ~/.pypirc
  - echo "[testpypi]"                                 >> ~/.pypirc
  - echo "repository=https://test.pypi.org/legacy/"   >> ~/.pypirc
  - echo "username=$PYPIUSER"                         >> ~/.pypirc
  - echo "password=$PYPIPASSWORD"                     >> ~/.pypirc

  # Publish python package
  - echo "PYPI deployment:"
  - if [ "$PYPI" != "true" ]; then echo "Not going to deploy because not configured to."; fi
  # Do not build pull requests
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then echo "Not going to deploy because pull request."; fi
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then PYPI=false; fi
  # Upload to pypi on master commits (if PYPI == true)
  - if [ "$PYPI" == "true" ] && [ "$TRAVIS_BRANCH" == "master" ]; then echo "Deploying to pypi because on master branch."; else echo "Not deploying to pypi."; fi
  - if [ "$PYPI" == "true" ] && [ "$TRAVIS_BRANCH" == "master" ]; then twine upload --skip-existing -r pypi dist/*; fi
  # Upload to testpypi on all commits (if PYPI == true)
  - if [ "$PYPI" == "true" ]; then echo "Deploying to testpypi."; else echo "Not deploying to testpypi."; fi
  - if [ "$PYPI" == "true" ]; then twine upload --skip-existing -r testpypi dist/*; fi
